image: node:5.0.0-slim
git:
  path: github.com/vjscjp304/testing
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/vjscjp304/testing
build:
  image: node:5.0.0-slim
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    username: $$bintray_user
    password: $$bintray_api_key
    registry: $$bintray_registry
    repo: $$bintray_repo
    email: $$bintray_user_email
    tag: $$COMMIT
    


notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "http://shipped-api.tx3.shipped-cisco.com/webhooks/drone"
    on_success: true
    on_failure: true
